# syntax=docker/dockerfile:1

FROM python:3.8-slim-buster

WORKDIR /code/

RUN pip install scipy
RUN pip install -U --no-cache-dir \
    matplotlib-label-lines==0.6.0 \
    scipy==1.10.1 \
    pandas==1.5.3


